 # **************************************************************
 # * File:			Makefile
 # * Author:		Šimon Stupinský
 # * University:	Brno University of Technology
 # * Faculty: 	 	Faculty of Information Technology
 # * Course:	    Computer Communications and Networks	
 # * Date:			09.04.2018
 # * Last change:	09.04.2018	
 # *		
 # * Subscribe:	Makefile
 # **************************************************************

all:
	gcc -g ipk-lookup.c stack.c ipk-lookup.h stack.h -o ipk-lookup

clean:
	rm -f *.o ipk-lookup
