 # **************************************************************
 # * File:			interface.h
 # * Author:		Šimon Stupinský
 # * University:	Brno University of Technology
 # * Faculty: 	 	Faculty of Information Technology
 # * Course:	    Computer Communications and Networks	
 # * Date:			02.03.2018
 # * Last change:	09.03.2018	
 # *		
 # * Subscribe:	Makefile
 # **************************************************************

all:
	g++ -static-libstdc++ -std=c++11 ipk-client.cpp -o ipk-client
	g++ -static-libstdc++ -std=c++11 ipk-server.cpp -o ipk-server

clean:
	rm -f *.o ipk-server ipk-client
